### PR TITLE
WIP #1716: M1 Compat

### PR DESCRIPTION
**Pull request by otbe**
updated protoc&grpc libs
switched to fabric8.io maven docker plugin

### CODE REVIEW

**Comment by uweschaefer** [comment]
why is the grpc upgrade necessary? in general, we should try to upgrade in sync with the spring grpc starter - is that possible?

**Comment by otbe** [comment]
Everything is possible 👀
If I solely upgrade the `protocArtifact/pluginArtiact` versions I get compile errors because of missing methods or classes. Ill try to find a working set of grpc/spring starter and protoc versions.

Im also not quite sure if the new docker plugin really works. The old one throwed exceptions due to a mismatch of architectures and its not updated anymore. The new one builds working images on my machine but Im not able to test the publication of images.

**Review by uweschaefer — APPROVED** [review]
lgtm, will test on release

**Comment by uweschaefer** [comment]
fixes #1716

**Pull request merged**
