### PR TITLE
issue1305 suppress warnings

### PR DESCRIPTION
**Pull request by uweschaefer**

### CODE REVIEW

**Comment by uweschaefer** [comment]
closes #1305

**Comment by samba2** [comment]
Thx für requesting a review. I'll have a thorough look when it's convenient. At first glance I was missing some tests for the logic in the enum.

**Comment by uweschaefer** [comment]
> Thx für requesting a review. I'll have a thorough look when it's convenient. At first glance I was missing some tests for the logic in the enum.

added tests

**Review by samba2 — APPROVED** [review]
lgtm

**Pull request merged**
