### PR TITLE
#684-fc-schema-cli-init-command-for-generate-raw-data-for-an-initial-…

### PR DESCRIPTION
**Pull request by BernhardBln**
solves #684

### CODE REVIEW

**Comment by BernhardBln** [comment]
No tests, as something awkward happens with the resources in intellij. tested manually.

**Comment by uweschaefer** [comment]
thx @BernhardBln 

Tests are still missing though...

**Comment by BernhardBln** [comment]
> thx @BernhardBln
> 
> Tests are still missing though...

@uweschaefer help with this is highly appreciated 😉

https://github.com/factcast/factcast/pull/1675#issuecomment-989143763

**Comment by uweschaefer** [comment]
obsolete by now

**Pull request closed without merging**
