### PR TITLE
issue1595: factus: handlers: filtering by annotation

### PR DESCRIPTION
**Pull request by uweschaefer**

### CODE REVIEW

**Comment by samba2** [comment]
doc: added some links and tried to make some statements more explicit. Pls double check

**Comment by samba2** [comment]
was just thinking. I see three ways of filtering which I would like to have contrasted (maybe at the filtering.md) page:
- server-side via new annotations (static)
- server-side via `postprocess` (dynamic, can be also in combination with annotations)
- client-side via handling the event and returning if a predicate is not matched (early return)

should we add this here?

**Comment by uweschaefer** [comment]
thx. i don't think we should advertise client side filtering at all, and usage of postprocess and these annotations is properly documented, imho

**Comment by samba2** [comment]
lgtm

**Review by samba2 — COMMENTED** [review]
lgtm

**Review by samba2 — APPROVED** [review]
lgtm

**Pull request merged**
