### PR TITLE
#2057: add buildx config for cross arch docker images

### PR DESCRIPTION
**Pull request by otbe**

### CODE REVIEW

**Comment by uweschaefer** [comment]
will be verified on 0.5.8 release

**Comment by uweschaefer** [comment]
does not seem to work on linux, also with credentials helper

**Comment by uweschaefer** [comment]
Retested with very current docker version and 0.40.2 of the fabric8 plugin

**Comment by uweschaefer** [comment]
using a rather ugly workaround to execute the push part outside of maven.

**Comment by otbe** [comment]
LGTM

**Comment by uweschaefer** [comment]
closes #2057

**Pull request merged**
